name: assistant-push
on:
  issue_comment:
    types: [created]

permissions: { contents: write, issues: write }

jobs:
  commit:
    if: startsWith(github.event.comment.body, '/assistant-commit')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { persist-credentials: true }  # uses built-in GITHUB_TOKEN

      - name: Parse path & content from comment
        id: vars
        run: |
          body="${{ github.event.comment.body }}"
          # remove the leading command
          payload="${body#/assistant-commit }"
          # first line = path, rest = content
          path="$(printf '%s\n' "$payload" | head -n1)"
          content="$(printf '%s\n' "$payload" | tail -n +2)"
          echo "PATH=$path"     >> $GITHUB_OUTPUT
          echo "CONTENT<<EOF"   >> $GITHUB_OUTPUT
          echo "$content"       >> $GITHUB_OUTPUT
          echo "EOF"            >> $GITHUB_OUTPUT

      - name: Write file
        run: |
          full="docs/${{ steps.vars.outputs.PATH }}"
          mkdir -p "$(dirname "$full")"
          printf '%s\n' "${{ steps.vars.outputs.CONTENT }}" > "$full"

      - name: Commit & push
        run: |
          git config user.name  "Solyn-Bot"
          git config user.email "actions@github.com"
          git add "docs/${{ steps.vars.outputs.PATH }}"
          git commit -m "[ENTRY] ${{ steps.vars.outputs.PATH }}" || echo "No changes"
          git push
          
      - name: Reply OK
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ **${{ steps.vars.outputs.PATH }}** saved & manifest will refresh.
